import base64
from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.graphics.shapes import Drawing, Line


def format_duration(seconds):
    seconds = int(seconds or 0)

    hours = seconds // 3600
    minutes = (seconds % 3600) // 60

    return f"{hours} hrs {minutes} mins"


def decode_chart(data_uri):
    """
    Converts a Chart.js base64 image into a ReportLab Image.
    """

    if not data_uri:
        return None

    if "," in data_uri:
        data_uri = data_uri.split(",", 1)[1]

    image_bytes = base64.b64decode(data_uri)

    image = BytesIO(image_bytes)

    reportlab_image = Image(
        image,
        width=7.1 * inch,
        height=4.0 * inch,
    )

    return reportlab_image


def create_summary_table(history):

    card_label = ParagraphStyle(
        "CardLabel",
        fontName="Helvetica-Bold",
        fontSize=10,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#1f4e78"),
    )
    
    card_value = ParagraphStyle(
        "CardValue",
        fontName="Helvetica-Bold",
        fontSize=20,
        alignment=TA_CENTER,
        textColor=colors.black,
    )

    rows = [[

        [
            Paragraph("TOTAL UPTIME", card_label),
            Spacer(1, 6),
            Paragraph(
                format_duration(history["total_uptime_seconds"]),
                card_value,
            )
        ],

        [
            Paragraph("TOTAL DOWNTIME", card_label),
            Spacer(1, 6),
            Paragraph(
                format_duration(history["total_downtime_seconds"]),
                card_value,
            )
        ],

        [
            Paragraph("EFFICIENCY", card_label),
            Spacer(1, 6),
            Paragraph(
                f'{history["weighted_efficiency_pct"]:.2f}%',
                card_value,
            )
        ],

    ]]

    table = Table(
        rows,
        colWidths=[2.3 * inch] * 3,
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#eef6fb")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#1f4e78")),
            ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c9d6df")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 18),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ])
    )

    return table


def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#555555"))

    canvas.drawString(
        25,
        18,
        "Generated by Machine Runtime Monitoring System"
    )

    canvas.drawRightString(
        570,
        18,
        f"Page {doc.page}"
    )

    canvas.restoreState()


def create_pdf_report(
    history,
    uptime_chart,
    trend_chart,
):

    pdf = BytesIO()

    document = SimpleDocTemplate(
        pdf,
        rightMargin=20,
        leftMargin=20,
        topMargin=25,
        bottomMargin=25,
    )

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    elements = []

    # ---------------------------------------------------
    # Header
    # ---------------------------------------------------

    elements.append(
        Paragraph(
            "<font size=20><b>MACHINE PERFORMANCE REPORT</b></font>",
            title,
        )
    )

    elements.append(Spacer(1, 0.12 * inch))

    generated = datetime.now().strftime("%d %b %Y %I:%M %p")

    info = Table(
        [
            ["Machine", history["machine"]],
            ["Period", f"{history['from_date']} to {history['to_date']}"],
            ["Generated", generated],
        ],
        colWidths=[1.3 * inch, 5.7 * inch],
    )

    info.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1f4e78")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    elements.append(info)

    elements.append(Spacer(1, 0.15 * inch))

    line = Drawing(520, 10)
    line.add(
        Line(
            0,
            5,
            520,
            5,
            strokeColor=colors.HexColor("#1f4e78"),
            strokeWidth=1,
        )
    )
    elements.append(line)
    elements.append(Spacer(1, 0.20 * inch))

    # ---------------------------------------------------
    # Summary
    # ---------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Summary Overview</b>",
            heading,
        )
    )

    elements.append(Spacer(1, 0.05 * inch))

    elements.append(
        create_summary_table(history)
    )

    elements.append(
        Spacer(1, 0.20 * inch)
    )

    # ---------------------------------------------------
    # Charts
    # ---------------------------------------------------

    uptime_image = decode_chart(uptime_chart)

    if uptime_image:
        elements.append(
            Paragraph(
                "<b>Uptime vs Downtime</b>",
                heading,
            )
        )

        elements.append(uptime_image)

        elements.append(
            Spacer(1, 0.15 * inch)
        )

    trend_image = decode_chart(trend_chart)

    if trend_image:
        elements.append(
            Paragraph(
                "<b>Efficiency Trend</b>",
                heading,
            )
        )

        elements.append(trend_image)

        elements.append(
            Spacer(1, 0.20 * inch)
        )

    # Move to Page 2 for Detailed Tables
    elements.append(PageBreak())

    # ---------------------------------------------------
    # Daily Performance Table
    # ---------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Daily Performance</b>",
            heading,
        )
    )

    elements.append(Spacer(1, 0.05 * inch))

    daily_rows = [
        [
            "Date",
            "Uptime",
            "Downtime",
            "Efficiency (%)",
        ]
    ]

    for row in history["daily"]:

        daily_rows.append(
            [
                row["date"],
                format_duration(
                    row["uptime_seconds"]
                ),
                format_duration(
                    row["downtime_seconds"]
                ),
                f'{row["efficiency_pct"]:.2f}',
            ]
        )

    daily_table = Table(
        daily_rows,
        repeatRows=1,
        colWidths=[1.8 * inch, 1.8 * inch, 1.8 * inch, 1.8 * inch],
    )

    daily_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e78")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
    ]

    for i in range(1, len(daily_rows)):
        row_color = colors.white if i % 2 != 0 else colors.HexColor("#f3f7fa")
        daily_style.append(("BACKGROUND", (0, i), (-1, i), row_color))
        daily_style.append(("BOTTOMPADDING", (0, i), (-1, i), 6))
        daily_style.append(("TOPPADDING", (0, i), (-1, i), 6))

    daily_table.setStyle(TableStyle(daily_style))

    elements.append(daily_table)

    elements.append(
        Spacer(1, 0.30 * inch)
    )

    # ---------------------------------------------------
    # Shift Performance Table
    # ---------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Shift Performance Records</b>",
            heading,
        )
    )

    elements.append(Spacer(1, 0.05 * inch))

    shift_rows = [
        [
            "Date",
            "Shift",
            "Uptime",
            "Downtime",
            "Efficiency (%)",
            "Status",
        ]
    ]

    for row in history["shifts"]:

        shift_rows.append(
            [
                row["date"],
                str(row["shift"]),
                format_duration(
                    row["uptime_seconds"]
                ),
                format_duration(
                    row["downtime_seconds"]
                ),
                f'{row["efficiency_pct"]:.2f}',
                "Final"
                if row["is_final"]
                else "In Progress",
            ]
        )

    shift_table = Table(
        shift_rows,
        repeatRows=1,
        colWidths=[1.4 * inch, 0.9 * inch, 1.4 * inch, 1.4 * inch, 1.4 * inch, 1.4 * inch],
    )

    shift_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e78")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
    ]

    for i in range(1, len(shift_rows)):
        row_color = colors.white if i % 2 != 0 else colors.HexColor("#f3f7fa")
        shift_style.append(("BACKGROUND", (0, i), (-1, i), row_color))
        shift_style.append(("BOTTOMPADDING", (0, i), (-1, i), 6))
        shift_style.append(("TOPPADDING", (0, i), (-1, i), 6))

    shift_table.setStyle(TableStyle(shift_style))

    elements.append(shift_table)

    document.build(
        elements,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    pdf.seek(0)

    return pdf