services:
  postgres:
    image: postgres:16-alpine
    container_name: machine_monitor_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: machine_monitor
      POSTGRES_USER: enter_username
      POSTGRES_PASSWORD: enter_password

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - machine_monitor_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data_logger -d machine_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  machine_monitor_pg_data:
